general:
  # Disable players to equip Elytras.
  # Players or groups with the permission 'elytraessentials.bypass.equipment' can bypass this restriction.
  disable-elytra-equipment: false # [Default: false]

  # Enable detailed debug messages in the server console.
  debug-mode: true # [Default: false]

flight:
  # Completely disable Elytra flight across all worlds.
  disable-global: false # [Default: false]

  # Specify worlds where Elytra flight is disabled.
  # World names are case-sensitive.
  disabled-worlds:
    - "custom_world"

  speed-limit:
    # Players or groups with the permission 'elytraessentials.bypass.speedlimit' can bypass this limit.
    enabled: true # [Default: true]

    # Default maximum flight speed in km/h.
    # Without rockets: ~36 km/h
    # With rockets (normal flight): ~108 km/h
    # With rockets (steep dive): ~180 km/h
    default: 75 # [Default: 75]

    # Per-world flight speed limits (overrides the default).
    per-world:
      custom_world: 50

  time-limit:
    # Players or groups with the permission 'elytraessentials.bypass.timelimit' can bypass this limit.
    enabled: false # [Default: false]

    database:
      host: localhost
      port: 3306
      database: elytraessentials
      username: root
      password: