# ----------------------------------------------------
#        ElytraEssentials - Main Configuration
# ----------------------------------------------------
#
# This file controls all core features of the plugin.
#
# Sections:
#   general: Toggles for plugin-wide features like debug mode and protections.
#   armored-elytra: Settings for the armored elytra feature.
#   storage: Configure your database settings (SQLite or MySQL).
#   flight:  Control all aspects of elytra mechanics like speed, time, worlds, boost and combat-tag.
#
# For messages, achievements and shop items, please see messages.yml, achievements.yml and shop.yml.

general:
  # Enable detailed debug messages in the server console.
  debug-mode: false # [Default: false]

  # Enables checking for newer versions of the plugin
  check-for-updates: true # [Default: true]

  # Disable players from equipping Elytras.
  # Players or groups with the permission 'elytraessentials.bypass.equipment' can bypass this restriction.
  disable-elytra-equipment: false # [Default: false]

  # Set to true to prevent players from taking fall damage when their elytra breaks mid-air.
  elytra-break-protection: false # [Default: false]

  # Set to true to prevent players from dying when they fly into a wall at high speed.
  # This will not prevent players from dying if they do a nosedive and hit the ground
  kinetic-energy-protection: false # [Default: false]

  # Set to true to automatically equip and deploy an elytra when
  # The minimum fall distance (in blocks) is verified by the plugin.
  emergency-deploy: false # [Default: false]

  # Set to true to prevent players from using firework rockets to boost while gliding.
  disable-firework-boosting: false # [Default: false]

  # Set to true to prevent players from launching themselves with Riptide tridents
  # while they are wearing an elytra. This does not affect normal, ground-based
  # Riptide movement when an elytra is not equipped.
  disable-riptide-launch: false # [Default: false]

armored-elytra:
  enabled: true # [Default: true]

  # The cost to forge or revert an Armored Elytra.
  # Set an amount to 0 to disable that specific cost.
  forging-cost:
    # The amount of money to charge for.
    money: 5000.0
    # The amount of experience levels to charge.
    xp-levels: 10

  # The cost to fully repair the Armor Plating.
  # Set an amount to 0 to disable that specific cost.
  repair-cost:
    money: 500.0
    xp-levels: 5

storage:
  # The type of storage to use.
  # Options: SQLITE (default), MYSQL
  type: SQLITE

  auto-backup:
    # Set to true to enable automatic backups of the database.
    enabled: true # [Default: true]

    # The interval (in minutes) at which to perform backups.
    interval: 60 # [Default: 60 minutes]

    # The maximum number of backup files to keep.
    max-backups: 24 # [Default: 24 backups]

  # --- MySQL Settings ---
  # These are ONLY used if 'type' is set to MYSQL.
  mysql:
    host: localhost
    port: 3306
    database: elytraessentials
    username: root
    password:

flight:
  # Completely disable Elytra flight across all worlds.
  disable-global: false # [Default: false]

  # Specify worlds where Elytra flight is disabled.
  # World names are case-sensitive.
  disabled-worlds:
    - "custom_world"

  speed-limit:
    # Players or groups with the permission 'elytraessentials.bypass.speedlimit' can bypass this limit.
    enabled: true # [Default: true]

    # Default maximum flight speed in km/h being 1 meter = 1 block
    default: 75 # [Default: 75]

    # Per-world flight speed limits (overrides the default).
    per-world:
      custom_world: 50

  time-limit:
    # Players or groups with the permission 'elytraessentials.bypass.timelimit' can bypass this limit.
    enabled: false # [Default: false]

    # The maximum flight time (in seconds) that a player can have.
    max-time: 600 # [Default: 600 seconds, 0 means unlimited]

    # Automatically restore flight time over a period of time.
    recovery:
      enabled: true # [Default: true]

      # The amount of flight time (in seconds) to add during recovery.
      amount: 10 # [Default: 10 seconds]

      # The interval (in seconds) at which to add the amount.
      interval: 60 # [Default: 60 seconds]

  boost:
    enabled: true # [Default: true]

    # For more, check this: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    item: FEATHER

    # Players or groups with the permission 'elytraessentials.bypass.boostcooldown' can bypass this cooldown.
    cooldown: 1000 # Cooldown time in milliseconds

    charged-jump:
      # Set to true to enable the charged jump feature from the ground.
      # If boost is not enabled, this will not work.
      enabled: true

      # The time in seconds it takes to fully charge the jump.
      charge-time: 2  # [Default: 2 seconds]

      # The strength of the upward launch. 1.5 is a strong vertical boost.
      jump-strength: 1.5

      # Set to true to enable a visual animation where blocks jump up when a player launches.
      enable-launch-animation: true # [Default: true]

  combat-tag:
    # Set to true to disable a player's elytra for a short time after they take damage while flying.
    enabled: true # [Default: true]

    # How long (in seconds) the player is prevented from gliding after being hit.
    duration: 10

    # If true, the player will be protected from the fall damage that occurs
    # immediately after their elytra is disabled by combat.
    prevent-fall-damage: true # [Default: true]

    # Set to true to only disable elytra from player-inflicted damage.
    # Set to false to disable elytra from ANY damage source (players, mobs, environment).
    player-damage-only: true  # [Default: true]

  tandem:
    # Set to true to enable the tandem flight (passenger system) feature.
    enabled: true # [Default: true]

    # How many seconds a player has to accept a /tandem invite before it expires.
    invite-timeout: 30 # [Default: 30 seconds]

    # Multiplier for flight time cost when carrying a passenger.
    # 2.0 means the driver consumes flight time twice as fast.
    # 1.0 means no extra cost (minimum value).
    flight-time-cost-multiplier: 2.0 # [Default: 2.0]

    # Protect passengers from fall damage when they are dismounted mid-air.
    protect-passenger-fall-damage: true # [Default: true]

    # How many seconds to count down before mounting a passenger after they accept.
    # Set to 0 to disable the countdown and mount instantly.
    mount-countdown: 3 # [Default: 3]