general:
  # Enable detailed debug messages in the server console.
  debug-mode: false # [Default: false]

  # Enables checking for newer versions of the plugin
  check-for-updates: true # [Default: true]

  # Disable players from equipping Elytras.
  # Players or groups with the permission 'elytraessentials.bypass.equipment' can bypass this restriction.
  disable-elytra-equipment: false # [Default: false]

  # Set to true to prevent players from taking fall damage when their elytra breaks mid-air.
  elytra-break-protection: false # [Default: false]

  # Set to true to prevent players from dying when they fly into a surface at high speed.
  # This will not prevent players from dying if they do a nosedive and hit the ground
  kinetic-energy-protection: false # [Default: false]

flight:
  # Completely disable Elytra flight across all worlds.
  disable-global: false # [Default: false]

  # Specify worlds where Elytra flight is disabled.
  # World names are case-sensitive.
  disabled-worlds:
    - "custom_world"

  speed-limit:
    # Players or groups with the permission 'elytraessentials.bypass.speedlimit' can bypass this limit.
    enabled: true # [Default: true]

    # Default maximum flight speed in km/h being 1 meter = 1 block
    default: 75 # [Default: 75]

    # Per-world flight speed limits (overrides the default).
    per-world:
      custom_world: 50

  time-limit:
    # Players or groups with the permission 'elytraessentials.bypass.timelimit' can bypass this limit.
    enabled: false # [Default: false]

    # The maximum flight time (in seconds) that a player can have.
    max-time: 600 # [Default: 600 seconds, 0 means unlimited]

    # Automatically restore flight time over a period of time.
    recovery:
      enabled: true # [Default: true]

      # The amount of flight time (in seconds) to add during recovery.
      amount: 10 # [Default: 10 seconds]

      # The interval (in seconds) at which to add the amount.
      interval: 60 # [Default: 60 seconds]

      # Notify players when flight time is recovered.
      notify: true # [Default: true]

    database:
      host: localhost
      port: 3306
      database: elytraessentials
      username: root
      password:

  boost:
    # For more, check this: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    item: FEATHER

    # Sound played when using this boost item
    # You can leave this empty if you wish to not play any sound
    # For more, check this: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    sound: 'BLOCK_BEACON_ACTIVATE'

    # Players or groups with the permission 'elytraessentials.bypass.boostcooldown' can bypass this cooldown.
    cooldown: 2000 # Cooldown time in milliseconds