name: ElytraEssentials
version: 1.0.0
main: org.bruno.elytraEssentials.ElytraEssentials
api-version: '1.21'
authors: [ CodingMaestro ]
description: A powerful plugin to manage Elytra flight and equipment features.
commands:
  elytraessentials:
    description: Main command for ElytraEssentials.
    usage: /ee <subcommand>
    aliases: [ ee ]
    permission: elytraessentials.command.use

permissions:
  elytraessentials.*:
    default: op
    description: "Grants access to all ElytraEssentials plugin features and commands."
    children:

      elytraessentials.command.*:
        default: op
        description: "Allows use of all ElytraEssentials commands."
        children:
          elytraessentials.command.use:
            default: true
            description: "Allows the use of the /ee base command and subcommands."
          elytraessentials.command.reload:
            default: op
            description: "Allows reloading the plugin configuration with /ee reload."
          elytraessentials.command.flighttime:
            default: op
            description: "Allows managing the flight time of a player with /ee flighttime add <player> <seconds>"

      elytraessentials.bypass.*:
        default: op
        description: "Allows bypassing all ElytraEssentials plugin restrictions and limits."
        children:
          elytraessentials.bypass.speedlimit:
            default: op
            description: "Bypasses the Elytra flight speed limits."
          elytraessentials.bypass.timelimit:
            default: op
            description: "Bypasses the Elytra flight time limits."
          elytraessentials.bypass.equipment:
            default: op
            description: "Bypasses restrictions on equipping Elytras."