main: org.bruno.elytraEssentials.ElytraEssentials
author: CodingMaestro
name: ElytraEssentials
version: 1.0.0
api-version: '1.21'
load: STARTUP
folia-supported: false
description: A powerful plugin to manage Elytra flight and equipment features.
website: https://www.spigotmc.org/resources/elytraessentials.126002/
depend: [Vault, PlaceholderAPI]
commands:
  elytraessentials:
    description: Main command for ElytraEssentials.
    usage: /ee <subcommand>
    aliases: [ ee ]
    permission: elytraessentials.command.use

permissions:
  elytraessentials.*:
    default: op
    description: "Grants access to all ElytraEssentials plugin features and commands."
    children:

      elytraessentials.command.*:
        default: op
        description: "Allows the use of all ElytraEssentials commands."
        children:
          elytraessentials.command.use:
            default: true
            description: "Allows the use of the /ee base command and subcommands."
          elytraessentials.command.reload:
            default: op
            description: "Allows reloading the plugin configuration with /ee reload."
          elytraessentials.command.flighttime:
            default: op
            description: "Allows managing flight time in a player with /ee ft commands"
          elytraessentials.command.shop:
            default: true
            description: "Allows the use of /ee shop command"
          elytraessentials.command.effects:
            default: true
            description: "Allows the use of /ee effects command"

      elytraessentials.bypass.*:
        default: op
        description: "Allows bypassing all ElytraEssentials plugin restrictions and limits."
        children:
          elytraessentials.bypass.speedlimit:
            default: op
            description: "Bypasses the Elytra flight speed limits."
          elytraessentials.bypass.timelimit:
            default: op
            description: "Bypasses the Elytra flight time limits."
          elytraessentials.bypass.equipment:
            default: op
            description: "Bypasses restrictions on equipping elytra."
          elytraessentials.bypass.boostcooldown:
            default: op
            description: "Bypasses restrictions on boost while flying with elytra"

      elytraessentials.update.notify:
        default: op
        description: "Allows the player to receive update notifications."

      elytraessentials.effect.*:
        default: op
        description: "Gives you access to all elytra effects"