main: org.bruno.elytraEssentials.ElytraEssentials
author: CodingMaestro
name: ElytraEssentials
version: 1.8.0
api-version: '1.18'
load: STARTUP
folia-supported: false
description: A powerful plugin to manage Elytra flight and equipment features.
website: https://www.spigotmc.org/resources/elytraessentials.126002/
depend: [Vault, PlaceholderAPI]
commands:
  elytraessentials:
    description: Main command for ElytraEssentials.
    usage: /ee <subcommand>
    aliases: [ ee ]
    permission: elytraessentials.command.use

permissions:
  elytraessentials.*:
    default: op
    description: "Grants access to all ElytraEssentials plugin features and commands."
    children:

      elytraessentials.command.*:
        default: op
        description: "Allows the use of all ElytraEssentials commands."
        children:
          elytraessentials.command.use:
            default: true
            description: "Allows the use of the /ee base command and subcommands."
          elytraessentials.command.reload:
            default: op
            description: "Allows reloading the plugin configuration with /ee reload."
          elytraessentials.command.flighttime:
            default: op
            description: "Allows managing flight time in a player with /ee ft commands"
          elytraessentials.command.shop:
            default: true
            description: "Allows the use of /ee shop command"
          elytraessentials.command.effects:
            default: true
            description: "Allows the use of /ee effects command"
          elytraessentials.command.effects.clear:
            default: true
            description: "Allows the use of /ee effects clear command"
          elytraessentials.command.effects.give:
            description: "Allows giving an effect to a player."
            default: op
          elytraessentials.command.effects.remove:
            description: "Allows removing an effect from a player."
            default: op
          elytraessentials.command.effects.list:
            description: "Allows listing the effects a player owns."
            default: op
          elytraessentials.command.stats:
            default: true
            description: "Allows the use of /ee stats command"
          elytraessentials.command.stats.others:
            default: op
            description: "Allows the use of /ee stats <player> command"
          elytraessentials.command.top:
            default: true
            description: "Allows the use of /ee top command"
          elytraessentials.command.forge:
            default: op
            description: "Allows the use of /ee forge command"
          elytraessentials.command.armor:
            default: true
            description: "Allows the use of /ee armor command"
          elytraessentials.command.armor.repair:
            default: true
            description: "Allows the use of /ee armor repair command"
          elytraessentials.command.importdb:
            default: op
            description: "Allows the use of /ee importdb command"
          elytraessentials.command.achievements:
            default: true
            description: "Allows the use of /ee achievements command"

      elytraessentials.bypass.*:
        default: op
        description: "Allows bypassing all ElytraEssentials plugin restrictions and limits."
        children:
          elytraessentials.bypass.speedlimit:
            default: op
            description: "Bypasses the Elytra flight speed limits."
          elytraessentials.bypass.timelimit:
            default: op
            description: "Bypasses the Elytra flight time limits."
          elytraessentials.bypass.equipment:
            default: op
            description: "Bypasses restrictions on equipping elytra."
          elytraessentials.bypass.boostcooldown:
            default: op
            description: "Bypasses restrictions on boost while flying with elytra."
          elytraessentials.bypass.combattag:
            default: op
            description: "Player will not be grounded by damage while flying."

      elytraessentials.update.notify:
        default: op
        description: "Allows the player to receive update notifications."

      elytraessentials.effect.*:
        default: op
        description: "Gives you access to all elytra effects"

      elytraessentials.elytra.boost:
        default: op
        description: "Allows the player to use the basic elytra boost with right click"
      elytraessentials.elytra.superboost:
        default: op
        description: "Allows the player to use the elytra super boost with right click + shift click"
      elytraessentials.elytra.chargedjump:
        default: op
        description: "Allows the player to use the elytra charged jump while holding the boost item"
      elytraessentials.elytra.autodeploy:
        default: op
        description: "Allows for automatic equipping and deployment of an elytra for a falling player to save him."