name: ElytraEssentials
version: 1.0.0
main: org.bruno.elytraEssentials.ElytraEssentials
api-version: '1.21'
authors: [ CodingMaestro ]
description: A powerful plugin to manage Elytra flight and equipment features.
commands:
  eereload:
    description: Reloads the plugins main configuration file.
    usage: /<command>
    permission: elytraessentials.command.reload

permissions:
  elytraessentials.*:
    default: op
    description: "Grants access to all ElytraEssentials plugin features and commands."
    children:

      elytraessentials.command.*:
        default: op
        description: "Allows use of all ElytraEssentials commands."
        children:
          elytraessentials.command.reload:
            default: op
            description: "Allows reloading the plugin configuration with /eereload."

      elytraessentials.bypass.*:
        default: op
        description: "Allows bypassing all ElytraEssentials plugin restrictions and limits."
        children:
          elytraessentials.bypass.speedlimit:
            default: op
            description: "Bypasses the Elytra flight speed limits."
          elytraessentials.bypass.equipment:
            default: op
            description: "Bypasses restrictions on equipping Elytras."