name: Create Plugin Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # --- THIS IS THE NEW PART ---
    # Use a matrix strategy to run the job for each profile
    strategy:
      matrix:
        profile: [ 'modern', 'legacy' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Commit Message
        id: get_commit_message
        run: echo "commit_message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      # Set a different Java version based on the profile
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.profile == 'legacy' && '17' || '21' }}
          distribution: 'temurin'
          cache: 'maven'

      # Build with Maven, activating the profile for the legacy build
      - name: Build with Maven
        run: mvn -B package --file pom.xml ${{ matrix.profile == 'legacy' && '-Pjava17-legacy' || '' }}
      
      # Rename the JAR file to include a suffix for the legacy build
      - name: Rename Legacy Artifact
        if: matrix.profile == 'legacy'
        run: mv target/ElytraEssentials-*.jar target/ElytraEssentials-${{ github.ref_name }}-legacy.jar

      # Rename the modern artifact for consistency
      - name: Rename Modern Artifact
        if: matrix.profile == 'modern'
        run: mv target/ElytraEssentials-*.jar target/ElytraEssentials-${{ github.ref_name }}-modern.jar

      # Upload the built JAR as an artifact so the next job can find it
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar-${{ matrix.profile }}
          path: target/ElytraEssentials-*.jar

  # --- NEW JOB TO CREATE THE RELEASE ---
  create-release:
    runs-on: ubuntu-latest

    # Grant this job the permission to write to the repository's contents,
    permissions:
      contents: write

    environment:
      name: production
      url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}

    # This job depends on the build-and-release job finishing for both profiles
    needs: build-and-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This step generates the full description and saves it to a file.
      - name: Generate Release Body
        run: |
          echo "### Supported Versions" >> release_body.md
          echo "\`ElytraEssentials-${{ github.ref_name }}-modern.jar\`: For Minecraft 1.21+ (JAVA 21)" >> release_body.md
          echo "\`ElytraEssentials-${{ github.ref_name }}-legacy.jar\`: For Minecraft 1.18.x - 1.20.4 (JAVA 17)" >> release_body.md
          echo "" >> release_body.md
          echo "---" >> release_body.md
          echo "" >> release_body.md
          echo "### Changelog" >> release_body.md
          PREVIOUS_TAG=$(git tag --sort=-v:refname | sed -n '2p')
          git log $PREVIOUS_TAG..${{ github.ref_name }} --pretty=format:'* %s' >> release_body.md

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          # Upload all JAR files from the artifacts directory
          body_path: release_body.md
          files: artifacts/*/*.jar
          prerelease: ${{ contains(github.ref_name, 'BETA') }}